name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # <-- CORREGIDO: Se agregaron los dos puntos

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Configuramos el SDK para la versión 10
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    # CORREGIDO: Se agregó 'src/' a la ruta del archivo del proyecto
    - name: Publish Blazor Project
      run: dotnet publish src/FedePortfolio.Web/FedePortfolio.Web.csproj -c Release -o release

    # CORREGIDO: Se cambió 'FedePortfolio' por el nombre real de tu repo que es 'Portfolio'
    - name: Change base-href
      run: sed -i 's/<base href="\/" \/>/<base href="\/Portfolio\/" \/>/g' release/wwwroot/index.html

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit and Push to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        branch: gh-pages
